name: dronify

packages:
  - apps/**
  - packages/**

# scripts:
 

#   # Example commands for running apps
#   app:android:
#     description: "Run the Flutter app on Android"
#     run: flutter run -d android

#   app:ios:
#     description: "Run the Flutter app on iOS"
#     run: flutter run -d ios